### PR TITLE
Add Copilot Pro support

### LINKED ISSUE #11: Bing: Support Copilot Pro
I've got Copilot Pro to do some testing and a few things about the request changed for both the free and pro tier.
I'll investigate these changes and see what needs to be added to get the most out of both modes.

### PR DESCRIPTION
**Pull request by Richard-Weiss**
This PR will resolve #11.
It's now possible to use Turbo when a cookie is used that has Copilot Pro and the toneStyle 'turbo' is passed.
There have also been some changes to get the request closer to the currently used one in vanilla Bing Chat.
The changes have been tested with the free and pro tier and there shouldn't be any regression bug.
Please report if any functionality isn't working anymore.

### CODE REVIEW

**Comment by vaibhavard** [comment]
Does this work with copilot for work ? Microsoft copilot that comes with 365?

**Comment by vaibhavard** [comment]
[Edit] : The turbo feature is not working for a work cookie : with following parameters:
    data = {
        "toneStyle":"turbo",
        "plugins":{"search":False},
        "message":query,
    }

**Comment by vaibhavard** [comment]
The ans. is of sydney bing and not gpt-4-turbo.

**Comment by Richard-Weiss** [comment]
@vaibhavard I don't have M365 Copilot, so I can't test it.  
You could send a request over the normal interface with turbo enabled and see how it differs to the current implementation.

**Pull request merged**
